Forms
MAPC/mapc-components pull request #4
Opened 2024-05-08 19:50 UTC by NotLiu

Implemented:

- Date Picker
- Multi-thumb Slider
- Number Slider (one thumb)
- Validation function workflow for user input controls
- Radio/Checkbox Buttons
- Selection/Dropdown Buttons
- Text Input controls
- Submit Button

2024-05-09 19:26 UTC, anaximander requested changes
This is looking pretty good! Left a few technical comments/nits here in addition to our discussion from earlier.

2024-05-09 19:26 UTC, anaximander commented on src/themes/colors.js
> +export const orangeTheme = {
👍

2024-06-06 18:15 UTC, anaximander approved these changes
This looks good, just noting a few changes we'll want to make as we continue to work on these:

- Datepicker should handle edge cases where current "value" is not a valid date string
- z-index adjustments for multiple thumb slider (thumb might be rendering under the line)
- We should look into ways of doing cross-browser/cross-OS testing as a team, so we can make sure all components work and render as expected on supported browsers/OSes

Ready to merge 👍

2024-06-06 18:33 UTC, NotLiu reviewed
lgtm

2024-06-06 18:39 UTC, merged